# Change these first
owner: crawlrabbit # Your GitHub organization or username
repo: PulseCheck # The name of this repository

sites:
  - name: Crawlrabbit
    url: https://crawlrabbit.com/

status-website:
  baseUrl: /PulseCheck
  name: Crawlrabbit Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Crawlrabbit System Status**"
  introMessage: Real-time uptime and performance monitoring for [Crawlrabbit](https://crawlrabbit.com/) - Your intelligent web crawling solution.
  navbar:
    - title: Status
      href: /
    - title: Visit Crawlrabbit
      href: https://crawlrabbit.com/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime configuration
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 * * * *"
  graphs: "0 * * * *"
  summary: "0 * * * *"
  site: "0 * * * *"
