# Change these first
owner: crawlrabbit # Your GitHub organization or username
repo: PulseCheck # The name of this repository

sites:
  - name: Crawlrabbit
    url: https://crawlrabbit.com/

status-website:
  # Use your own domain if you have one, otherwise comment this out
  # cname: demo.upptime.js.org
  baseUrl: /PulseCheck
  name: CrawlRabbit

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Crawlrabbit Status
  introTitle: "**Crawlrabbit Status Page**"
  introMessage: Live uptime and performance monitoring for Crawlrabbit.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
